#!/usr/bin/env python3
"""Lock and verify the Python environment used for Windows releases."""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUTS = (
    Path("windows/requirements.txt"),
    Path("windows/requirements-build.txt"),
    Path("windows/requirements-cuda.txt"),
)
LOCK = ROOT / "windows/requirements-release.txt"
PYTHON_VERSION = "3.12.14"
TARGET = "x86_64-pc-windows-msvc"
PIN_RE = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s;]+)$")
NAME_RE = re.compile(r"^([A-Za-z0-9_.-]+)")


def canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def input_fingerprint() -> str:
    digest = hashlib.sha256()
    for relative in INPUTS:
        digest.update(relative.as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update((ROOT / relative).read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def header(body: str) -> str:
    body_digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    return (
        "# Generated by windows/release_requirements.py for Windows x86-64\n"
        f"# and CPython {PYTHON_VERSION}. CUDA Torch remains in requirements-cuda.txt.\n"
        f"# Inputs SHA-256: {input_fingerprint()}\n"
        f"# Resolution SHA-256: {body_digest}\n"
        "# Regenerate with: python windows/release_requirements.py\n"
    )


def requirement_names(path: Path) -> set[str]:
    names: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", "--")):
            continue
        match = NAME_RE.match(line)
        if not match:
            raise ValueError(f"{path}: unsupported requirement: {raw}")
        names.add(canonical_name(match.group(1)))
    return names


def torch_version() -> str:
    text = (ROOT / INPUTS[2]).read_text(encoding="utf-8")
    matches = re.findall(r"(?m)^torch==([^\s]+)$", text)
    if len(matches) != 1:
        raise ValueError("requirements-cuda.txt must contain one exact Torch pin")
    return matches[0]


def pin_map(text: str) -> dict[str, str]:
    pins: dict[str, str] = {}
    ordered: list[str] = []
    for raw in text.splitlines():
        if not raw or raw.startswith(("#", " ", "\t")):
            continue
        match = PIN_RE.fullmatch(raw)
        if not match:
            raise ValueError(f"release lock contains a non-exact requirement: {raw}")
        name = canonical_name(match.group(1))
        if name in pins:
            raise ValueError(f"release lock contains duplicate package: {name}")
        pins[name] = match.group(2)
        ordered.append(name)
    if ordered != sorted(ordered):
        raise ValueError("release lock packages must be sorted by canonical name")
    return pins


def validate(text: str) -> dict[str, str]:
    lines = text.splitlines(keepends=True)
    body = "".join(lines[5:])
    if "".join(lines[:5]) != header(body):
        raise ValueError("release lock header, inputs, or resolution fingerprint is stale")
    pins = pin_map(body)
    required = requirement_names(ROOT / INPUTS[0]) | requirement_names(ROOT / INPUTS[1])
    missing = sorted(required - pins.keys())
    if missing:
        raise ValueError("release lock is missing direct requirements: " + ", ".join(missing))
    if "torch" in pins:
        raise ValueError("CUDA Torch must remain isolated in requirements-cuda.txt")
    torch_version()
    return pins


def without_torch(compiled: str) -> str:
    lines = compiled.splitlines()
    output: list[str] = []
    index = 0
    removed = False
    while index < len(lines):
        line = lines[index]
        match = PIN_RE.fullmatch(line)
        if match and canonical_name(match.group(1)) == "torch":
            removed = True
            index += 1
            while index < len(lines) and lines[index].startswith((" ", "\t")):
                index += 1
            continue
        output.append(line)
        index += 1
    if not removed:
        raise ValueError("resolver output did not contain Torch")
    return "\n".join(output).rstrip() + "\n"


def generate() -> None:
    uv = shutil.which("uv")
    if not uv:
        raise SystemExit(
            "uv is required to regenerate the Windows release lock: "
            "https://docs.astral.sh/uv/"
        )
    cpu_version = torch_version().split("+", 1)[0]
    with tempfile.TemporaryDirectory(prefix="presspeech-windows-lock-") as temporary:
        temporary_path = Path(temporary)
        torch_input = temporary_path / "torch.in"
        output = temporary_path / "requirements.txt"
        # Resolve the PyPI wheel only for dependency metadata. The actual CUDA
        # local-version wheel stays pinned to its isolated index.
        torch_input.write_text(f"torch=={cpu_version}\n", encoding="utf-8")
        command = [
            uv,
            "pip",
            "compile",
            str(INPUTS[0]),
            str(INPUTS[1]),
            str(torch_input),
            "--python-platform",
            TARGET,
            "--python-version",
            PYTHON_VERSION,
            "--only-binary",
            ":all:",
            "--upgrade",
            "--no-cache",
            "--no-header",
            "--output-file",
            str(output),
        ]
        subprocess.run(command, cwd=ROOT, check=True)
        body = without_torch(output.read_text(encoding="utf-8"))
    result = header(body) + body
    validate(result)
    LOCK.write_text(result, encoding="utf-8", newline="\n")
    print(f"wrote {LOCK.relative_to(ROOT)} ({len(pin_map(body))} packages)")


def environment_errors(
    installed: dict[str, str], python_version: tuple[int, int, int]
) -> list[str]:
    pins = validate(LOCK.read_text(encoding="utf-8"))
    pins["torch"] = torch_version()
    errors: list[str] = []
    expected_python = tuple(int(part) for part in PYTHON_VERSION.split("."))
    if python_version != expected_python:
        errors.append(
            f"Python is {'.'.join(map(str, python_version))}; expected {PYTHON_VERSION}"
        )
    for name, expected in sorted(pins.items()):
        actual = installed.get(name)
        if actual is None:
            errors.append(f"{name} is not installed; expected {expected}")
        elif actual != expected:
            errors.append(f"{name} is {actual}; expected {expected}")
    return errors


def verify_environment() -> None:
    installed = {
        canonical_name(distribution.metadata["Name"]): distribution.version
        for distribution in importlib.metadata.distributions()
        if distribution.metadata["Name"]
    }
    errors = environment_errors(installed, sys.version_info[:3])
    if errors:
        raise ValueError("release environment does not match the lock:\n  " + "\n  ".join(errors))
    print(f"Windows release environment matches {LOCK.name}.")


def self_test() -> None:
    assert canonical_name("PyInstaller_Hooks.Contrib") == "pyinstaller-hooks-contrib"
    sample = "alpha==1\n    # via root\ntorch==2+cu126\n    # via input\nzeta==3\n"
    assert without_torch(sample) == "alpha==1\n    # via root\nzeta==3\n"
    assert pin_map("alpha==1\nzeta==3\n") == {"alpha": "1", "zeta": "3"}
    for bad in ("zeta==3\nalpha==1\n", "alpha>=1\n", "alpha==1\nalpha==2\n"):
        try:
            pin_map(bad)
        except ValueError:
            pass
        else:
            raise AssertionError(f"accepted invalid lock: {bad!r}")
    print("Windows release requirement self-test passed.")


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="validate the committed lock")
    mode.add_argument("--verify-environment", action="store_true")
    mode.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        self_test()
    elif args.verify_environment:
        verify_environment()
    elif args.check:
        validate(LOCK.read_text(encoding="utf-8"))
        print("Windows release requirement lock is current.")
    else:
        generate()


if __name__ == "__main__":
    try:
        main()
    except ValueError as error:
        raise SystemExit(str(error)) from None
