#!/usr/bin/env python3
"""Lock and verify the Python environment used for Windows releases."""

from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
from html.parser import HTMLParser
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.parse import unquote, urlparse
from urllib.request import HTTPRedirectHandler, build_opener


ROOT = Path(__file__).resolve().parents[1]
INPUTS = (
    Path("windows/requirements.txt"),
    Path("windows/requirements-build.txt"),
    Path("windows/requirements-cuda.txt"),
    Path("windows/requirements-cuda-release.txt"),
)
LOCK = ROOT / "windows/requirements-release.txt"
# Python 3.12.10 is the final 3.12 release with official Windows installers.
# Later 3.12 security releases are source-only and cannot be provisioned by
# actions/setup-python on a hosted Windows release runner.
PYTHON_VERSION = "3.12.10"
TARGET = "x86_64-pc-windows-msvc"
PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9_.-]*)==([A-Za-z0-9][A-Za-z0-9.!+_-]*)(?:\s+\\)?$")
HASH_RE = re.compile(r"^\s+--hash=sha256:([0-9a-f]{64})(\s+\\)?$")
NAME_RE = re.compile(r"^([A-Za-z0-9_.-]+)")


def canonical_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def normalized_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")


def input_fingerprint(overrides: dict[Path, str] | None = None) -> str:
    digest = hashlib.sha256()
    for relative in INPUTS:
        digest.update(relative.as_posix().encode("utf-8"))
        digest.update(b"\0")
        text = overrides[relative] if overrides and relative in overrides else normalized_text(ROOT / relative)
        digest.update(text.encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()


def header(body: str, overrides: dict[Path, str] | None = None) -> str:
    body_digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    return (
        "# Generated by windows/release_requirements.py; hash-locked for Windows x86-64\n"
        f"# and CPython {PYTHON_VERSION}. CUDA Torch remains in requirements-cuda.txt.\n"
        f"# Inputs SHA-256: {input_fingerprint(overrides)}\n"
        f"# Resolution SHA-256: {body_digest}\n"
        "# Regenerate with: python windows/release_requirements.py\n"
    )


def requirement_names(path: Path) -> set[str]:
    names: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith(("#", "--")):
            continue
        match = NAME_RE.match(line)
        if not match:
            raise ValueError(f"{path}: unsupported requirement: {raw}")
        names.add(canonical_name(match.group(1)))
    return names


def torch_version() -> str:
    text = (ROOT / INPUTS[2]).read_text(encoding="utf-8")
    matches = re.findall(r"(?m)^torch==([^\s]+)$", text)
    if len(matches) != 1:
        raise ValueError("requirements-cuda.txt must contain one exact Torch pin")
    return matches[0]


def cuda_source() -> tuple[str, str]:
    lines = [line.strip() for line in normalized_text(ROOT / INPUTS[2]).splitlines()
             if line.strip() and not line.lstrip().startswith("#")]
    if len(lines) != 2:
        raise ValueError("CUDA source requires only its index and exact Torch pin")
    index = re.fullmatch(r"--index-url (https://download\.pytorch\.org/whl/(cu[0-9]+))", lines[0])
    pin = re.fullmatch(r"torch==([0-9]+\.[0-9]+\.[0-9]+\+(cu[0-9]+))", lines[1])
    if not index or not pin or index[2] != pin[2]:
        raise ValueError("CUDA source index and Torch build must match")
    return index[1], pin[1]


def cuda_lock_text(digest: str) -> str:
    if not re.fullmatch(r"[0-9a-f]{64}", digest):
        raise ValueError("CUDA artifact requires one SHA-256 digest")
    index, version = cuda_source()
    source_digest = hashlib.sha256(normalized_text(ROOT / INPUTS[2]).encode()).hexdigest()
    return (
        "# Generated by windows/release_requirements.py for CPython 3.12 Windows x86-64\n"
        f"# Source SHA-256: {source_digest}\n"
        f"--index-url {index}\n\n"
        f"torch=={version} " + '\\\n' + f"    --hash=sha256:{digest}\n"
    )


def validate_cuda_lock(text: str) -> str:
    hashes = re.findall(r"(?m)^    --hash=sha256:([0-9a-f]{64})$", text)
    if len(hashes) != 1 or text != cuda_lock_text(hashes[0]):
        raise ValueError("CUDA release lock is stale or is not one exact hash-locked Torch artifact")
    return hashes[0]


def cuda_artifact_digest(index_html: str, index: str, version: str) -> str:
    if index != "https://download.pytorch.org/whl/" + version.split("+", 1)[1]:
        raise ValueError("CUDA artifact index and version disagree")
    wheel = f"torch-{version}-cp312-cp312-win_amd64.whl"
    path = f"/whl/{version.split('+', 1)[1]}/{wheel}"
    digests: set[str] = set()
    class Links(HTMLParser):
        def handle_starttag(self, tag, attrs):
            if tag != "a":
                return
            url = urlparse(dict(attrs).get("href", ""))
            if (url.scheme == "https" and url.netloc in {"download.pytorch.org", "download-r2.pytorch.org"}
                    and not url.query and unquote(url.path) == path):
                match = re.fullmatch(r"sha256=([0-9a-f]{64})", url.fragment)
                if not match:
                    raise ValueError("official CUDA wheel link lacks a SHA-256 digest")
                digests.add(match[1])
    Links().feed(index_html)
    if len(digests) != 1:
        raise ValueError("official CUDA index must identify exactly one CPython 3.12 Windows artifact digest")
    return digests.pop()


class CudaMetadataRedirectHandler(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        # Check the boundary before urllib opens a second connection. A final
        # response URL check alone runs after contacting the redirect target.
        fp.close()
        raise ValueError("CUDA index redirects are not permitted")


def resolved_cuda_lock() -> str:
    index, version = cuda_source()
    opener = build_opener(CudaMetadataRedirectHandler())
    with opener.open(index + "/torch/", timeout=30) as response:
        if response.url != index + "/torch/":
            raise ValueError("unexpected CUDA index redirect")
        data = response.read(2_000_001)
    if len(data) > 2_000_000:
        raise ValueError("CUDA index response exceeds the metadata limit")
    return cuda_lock_text(cuda_artifact_digest(data.decode("utf-8"), index, version))


def pin_map(text: str) -> dict[str, str]:
    """Parse an exact, SHA-256-locked requirements body."""
    pins: dict[str, str] = {}
    ordered: list[str] = []
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        raw = lines[index]
        if not raw or raw.startswith("#"):
            index += 1
            continue
        match = PIN_RE.fullmatch(raw)
        if not match:
            raise ValueError(f"release lock contains a non-exact requirement: {raw}")
        name = canonical_name(match.group(1))
        if name in pins:
            raise ValueError(f"release lock contains duplicate package: {name}")
        pins[name] = match.group(2)
        ordered.append(name)
        if not raw.endswith("\\"):
            raise ValueError(f"release lock requirement has no SHA-256 hash: {name}")

        hashes: list[str] = []
        continued = True
        index += 1
        while index < len(lines) and lines[index].lstrip().startswith("--hash"):
            if not continued:
                raise ValueError(f"release lock has a detached hash for {name}")
            hash_match = HASH_RE.fullmatch(lines[index])
            if not hash_match:
                raise ValueError(f"release lock has an invalid SHA-256 hash for {name}")
            digest = hash_match.group(1)
            if digest in hashes:
                raise ValueError(f"release lock has a duplicate SHA-256 hash for {name}")
            hashes.append(digest)
            continued = hash_match.group(2) is not None
            index += 1
        if not hashes:
            raise ValueError(f"release lock requirement has no SHA-256 hash: {name}")
        if continued:
            raise ValueError(f"release lock hash continuation is incomplete for {name}")

        while index < len(lines) and (
                not lines[index]
                or (lines[index].startswith((" ", "\t"))
                    and lines[index].lstrip().startswith("#"))):
            index += 1
    if ordered != sorted(ordered):
        raise ValueError("release lock packages must be sorted by canonical name")
    return pins


def validate(text: str, overrides: dict[Path, str] | None = None) -> dict[str, str]:
    lines = text.splitlines(keepends=True)
    body = "".join(lines[5:])
    if "".join(lines[:5]) != header(body, overrides):
        raise ValueError("release lock header, inputs, or resolution fingerprint is stale")
    pins = pin_map(body)
    required = requirement_names(ROOT / INPUTS[0]) | requirement_names(ROOT / INPUTS[1])
    missing = sorted(required - pins.keys())
    if missing:
        raise ValueError("release lock is missing direct requirements: " + ", ".join(missing))
    if "torch" in pins:
        raise ValueError("CUDA Torch must remain isolated in requirements-cuda.txt")
    cuda_text = overrides[INPUTS[3]] if overrides and INPUTS[3] in overrides else normalized_text(ROOT / INPUTS[3])
    validate_cuda_lock(cuda_text)
    return pins


def without_torch(compiled: str) -> str:
    lines = compiled.splitlines()
    output: list[str] = []
    index = 0
    removed = False
    while index < len(lines):
        line = lines[index]
        match = PIN_RE.fullmatch(line)
        if match and canonical_name(match.group(1)) == "torch":
            removed = True
            index += 1
            while index < len(lines) and lines[index].startswith((" ", "\t")):
                index += 1
            continue
        output.append(line)
        index += 1
    if not removed:
        raise ValueError("resolver output did not contain Torch")
    return "\n".join(output).rstrip() + "\n"


def generate() -> None:
    uv = shutil.which("uv")
    if not uv:
        raise SystemExit(
            "uv is required to regenerate the Windows release lock: "
            "https://docs.astral.sh/uv/"
        )
    cpu_version = torch_version().split("+", 1)[0]
    with tempfile.TemporaryDirectory(prefix="presspeech-windows-lock-") as temporary:
        temporary_path = Path(temporary)
        torch_input = temporary_path / "torch.in"
        output = temporary_path / "requirements.txt"
        # Resolve the PyPI wheel only for dependency metadata. The actual CUDA
        # local-version wheel stays pinned to its isolated index.
        torch_input.write_text(f"torch=={cpu_version}\n", encoding="utf-8")
        command = [
            uv,
            "pip",
            "compile",
            str(INPUTS[0]),
            str(INPUTS[1]),
            str(torch_input),
            "--python-platform",
            TARGET,
            "--python-version",
            PYTHON_VERSION,
            "--only-binary",
            ":all:",
            "--generate-hashes",
            "--upgrade",
            "--no-cache",
            "--no-header",
            "--output-file",
            str(output),
        ]
        subprocess.run(command, cwd=ROOT, check=True)
        body = without_torch(output.read_text(encoding="utf-8"))
    cuda_text = resolved_cuda_lock()
    overrides = {INPUTS[3]: cuda_text}
    result = header(body, overrides) + body
    validate(result, overrides)
    (ROOT / INPUTS[3]).write_text(cuda_text, encoding="utf-8", newline="\n")
    LOCK.write_text(result, encoding="utf-8", newline="\n")
    print(f"wrote {LOCK.relative_to(ROOT)} ({len(pin_map(body))} packages)")


def environment_errors(
    installed: dict[str, str], python_version: tuple[int, int, int]
) -> list[str]:
    pins = validate(LOCK.read_text(encoding="utf-8"))
    pins["torch"] = torch_version()
    errors: list[str] = []
    expected_python = tuple(int(part) for part in PYTHON_VERSION.split("."))
    if python_version != expected_python:
        errors.append(
            f"Python is {'.'.join(map(str, python_version))}; expected {PYTHON_VERSION}"
        )
    for name, expected in sorted(pins.items()):
        actual = installed.get(name)
        if actual is None:
            errors.append(f"{name} is not installed; expected {expected}")
        elif actual != expected:
            errors.append(f"{name} is {actual}; expected {expected}")
    return errors


def verify_environment() -> None:
    installed = {
        canonical_name(distribution.metadata["Name"]): distribution.version
        for distribution in importlib.metadata.distributions()
        if distribution.metadata["Name"]
    }
    errors = environment_errors(installed, sys.version_info[:3])
    if errors:
        raise ValueError("release environment does not match the lock:\n  " + "\n  ".join(errors))
    print(f"Windows release environment matches {LOCK.name}.")


def self_test() -> None:
    assert canonical_name("PyInstaller_Hooks.Contrib") == "pyinstaller-hooks-contrib"
    a_hash = "a" * 64
    b_hash = "b" * 64
    sample = (
        f"alpha==1 \\\n    --hash=sha256:{a_hash}\n"
        "    # via root\n"
        f"torch==2+cu126 \\\n    --hash=sha256:{b_hash}\n"
        "    # via input\n"
        f"zeta==3 \\\n    --hash=sha256:{b_hash}\n"
    )
    assert without_torch(sample) == (
        f"alpha==1 \\\n    --hash=sha256:{a_hash}\n"
        "    # via root\n"
        f"zeta==3 \\\n    --hash=sha256:{b_hash}\n"
    )
    assert pin_map(
        f"alpha==1 \\\n    --hash=sha256:{a_hash}\n"
        f"zeta==3 \\\n    --hash=sha256:{b_hash}\n"
    ) == {"alpha": "1", "zeta": "3"}
    bad_locks = (
        f"zeta==3 \\\n    --hash=sha256:{a_hash}\n"
        f"alpha==1 \\\n    --hash=sha256:{b_hash}\n",
        "alpha>=1\n",
        f"alpha==1 \\\n    --hash=sha256:{a_hash}\n"
        f"alpha==2 \\\n    --hash=sha256:{b_hash}\n",
        "alpha==1\n",
        "alpha==1 \\\n    --hash=sha256:not-a-digest\n",
        f"alpha==1 \\\n    --hash=sha256:{a_hash} \\\n",
    )
    for bad in bad_locks:
        try:
            pin_map(bad)
        except ValueError:
            pass
        else:
            raise AssertionError(f"accepted invalid lock: {bad!r}")
    print("Windows release requirement self-test passed.")


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="validate the committed lock")
    mode.add_argument("--verify-environment", action="store_true")
    mode.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        self_test()
    elif args.verify_environment:
        verify_environment()
    elif args.check:
        validate(LOCK.read_text(encoding="utf-8"))
        print("Windows release requirement lock is current.")
    else:
        generate()


if __name__ == "__main__":
    try:
        main()
    except ValueError as error:
        raise SystemExit(str(error)) from None
